package GUI;

import app.Employee;
import app.PayrollEditor;
import app.Tax;
import filehandling.Writer;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.NoSuchElementException;
import utils.PayrollInterface;

/**
 *
 * @author MP
 */
public class InputFrame extends javax.swing.JFrame {

    public static PayrollInterface pay;

    /**
     * Creates new form InputFrame
     */
    public InputFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneEW = new javax.swing.JTabbedPane();
        EmplMenuPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelLoadShowEmpls = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        tfEnterFileEmpl = new java.awt.TextField();
        lbMakeFileMessage = new javax.swing.JLabel();
        btnMakeNewFile = new javax.swing.JButton();
        btnShowEmpls = new javax.swing.JButton();
        EmployeeTextArea = new java.awt.TextArea();
        btnEmplsSortByID = new javax.swing.JButton();
        btnEmplsSortByFirstName = new javax.swing.JButton();
        btnEmplsSortByLastName = new javax.swing.JButton();
        btnFindEmplByID = new javax.swing.JButton();
        jLabelSearchForID = new javax.swing.JLabel();
        jTextFieldEmplSearchForID = new javax.swing.JTextField();
        jLabelEmplsSorting = new javax.swing.JLabel();
        jPanelAddNewEmpl = new javax.swing.JPanel();
        btnAddEmpl = new javax.swing.JButton();
        jPaneladdEmplData = new javax.swing.JPanel();
        jTextFieldeID = new javax.swing.JTextField();
        jLabeleID = new javax.swing.JLabel();
        jLabeleName = new javax.swing.JLabel();
        jTextFieldeName = new javax.swing.JTextField();
        jLabeleLastName = new javax.swing.JLabel();
        jTextFieldeLastName = new javax.swing.JTextField();
        jLabeleDateOfBirth = new javax.swing.JLabel();
        jTextFieldeedd = new javax.swing.JTextField();
        jLabeleNationality = new javax.swing.JLabel();
        jTextFieldeNationality = new javax.swing.JTextField();
        jLabeleHourTax = new javax.swing.JLabel();
        jTextFieldeHourTax = new javax.swing.JTextField();
        jLabelePositionName = new javax.swing.JLabel();
        jTextFieldePositionName = new javax.swing.JTextField();
        jLabeledd = new javax.swing.JLabel();
        jLabelemm = new javax.swing.JLabel();
        jTextFieldemm = new javax.swing.JTextField();
        jLabeleyyyy = new javax.swing.JLabel();
        jTextFieldeyyyy = new javax.swing.JTextField();
        btnEmplShowBeforeAdd = new javax.swing.JButton();
        textAreaShowListAfterAddedEmpl = new java.awt.TextArea();
        btnEmplsSaveAddedEmpl = new javax.swing.JButton();
        jLabelErrorMessageAddEmpl = new javax.swing.JLabel();
        WageMenuPanel = new javax.swing.JPanel();
        jTextFieldWageFilePath = new javax.swing.JTextField();
        jLabelWageFileWhours = new javax.swing.JLabel();
        jLabelWageEnterFileMessage = new javax.swing.JLabel();
        jButtonWageMakeNewFile = new javax.swing.JButton();
        WageTextArea = new java.awt.TextArea();
        jButtonWageShowHours = new javax.swing.JButton();
        jButtonWageCalculateWage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payroll app");
        setMinimumSize(new java.awt.Dimension(912, 500));

        jLabel1.setText("Enter file with employees");

        tfEnterFileEmpl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEnterFileEmplKeyPressed(evt);
            }
        });

        btnMakeNewFile.setText("MakeNewFile");
        btnMakeNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeNewFileActionPerformed(evt);
            }
        });

        btnShowEmpls.setText("ShowEmployeesInfo");
        btnShowEmpls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowEmplsActionPerformed(evt);
            }
        });

        btnEmplsSortByID.setText("SortByID");
        btnEmplsSortByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmplsSortByIDActionPerformed(evt);
            }
        });

        btnEmplsSortByFirstName.setText("SortByFirstName");
        btnEmplsSortByFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmplsSortByFirstNameActionPerformed(evt);
            }
        });

        btnEmplsSortByLastName.setText("SortByLastName");
        btnEmplsSortByLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmplsSortByLastNameActionPerformed(evt);
            }
        });

        btnFindEmplByID.setText("FindEmployeeByID");
        btnFindEmplByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindEmplByIDActionPerformed(evt);
            }
        });

        jLabelSearchForID.setText("Enter ID to search Employee");

        jLabelEmplsSorting.setText("For SORT click on button");

        javax.swing.GroupLayout jPanelLoadShowEmplsLayout = new javax.swing.GroupLayout(jPanelLoadShowEmpls);
        jPanelLoadShowEmpls.setLayout(jPanelLoadShowEmplsLayout);
        jPanelLoadShowEmplsLayout.setHorizontalGroup(
            jPanelLoadShowEmplsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoadShowEmplsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLoadShowEmplsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoadShowEmplsLayout.createSequentialGroup()
                        .addGroup(jPanelLoadShowEmplsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLoadShowEmplsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnShowEmpls, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(btnEmplsSortByFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEmplsSortByID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEmplsSortByLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSearchForID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelEmplsSorting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelLoadShowEmplsLayout.createSequentialGroup()
                                .addComponent(jTextFieldEmplSearchForID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFindEmplByID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanelLoadShowEmplsLayout.createSequentialGroup()
                        .addGroup(jPanelLoadShowEmplsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbMakeFileMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                            .addComponent(tfEnterFileEmpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnMakeNewFile, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLoadShowEmplsLayout.setVerticalGroup(
            jPanelLoadShowEmplsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoadShowEmplsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoadShowEmplsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLoadShowEmplsLayout.createSequentialGroup()
                        .addComponent(tfEnterFileEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMakeFileMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMakeNewFile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoadShowEmplsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLoadShowEmplsLayout.createSequentialGroup()
                        .addComponent(btnShowEmpls, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEmplsSorting)
                        .addGap(2, 2, 2)
                        .addComponent(btnEmplsSortByID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmplsSortByFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmplsSortByLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSearchForID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelLoadShowEmplsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFindEmplByID, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmplSearchForID))
                        .addGap(34, 34, 34))))
        );

        jTabbedPane1.addTab("Load and Show Employee file", jPanelLoadShowEmpls);

        btnAddEmpl.setText("AddEmployee");
        btnAddEmpl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddEmpl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmplActionPerformed(evt);
            }
        });

        jLabeleID.setText("ID");

        jLabeleName.setText("FirstName");

        jLabeleLastName.setText("LastName");

        jLabeleDateOfBirth.setText("DateOfBirth");

        jLabeleNationality.setText("Nationality");

        jLabeleHourTax.setText("HourTax");

        jLabelePositionName.setText("PositionName");

        jLabeledd.setText("dd");

        jLabelemm.setText("mm");

        jLabeleyyyy.setText("yyyy");

        btnEmplShowBeforeAdd.setText("ShowEmployee");
        btnEmplShowBeforeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmplShowBeforeAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneladdEmplDataLayout = new javax.swing.GroupLayout(jPaneladdEmplData);
        jPaneladdEmplData.setLayout(jPaneladdEmplDataLayout);
        jPaneladdEmplDataLayout.setHorizontalGroup(
            jPaneladdEmplDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneladdEmplDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneladdEmplDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabeleID)
                    .addComponent(jTextFieldeID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeleName)
                    .addComponent(jTextFieldeName)
                    .addComponent(jLabeleLastName)
                    .addComponent(jTextFieldeLastName)
                    .addComponent(jLabeleDateOfBirth)
                    .addComponent(jLabeleNationality)
                    .addComponent(jTextFieldeNationality)
                    .addComponent(jLabeleHourTax)
                    .addComponent(jTextFieldeHourTax)
                    .addComponent(jLabelePositionName)
                    .addComponent(jTextFieldePositionName)
                    .addGroup(jPaneladdEmplDataLayout.createSequentialGroup()
                        .addComponent(jLabeledd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldeedd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelemm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldemm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)))
                .addGroup(jPaneladdEmplDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneladdEmplDataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabeleyyyy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldeyyyy, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneladdEmplDataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEmplShowBeforeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPaneladdEmplDataLayout.setVerticalGroup(
            jPaneladdEmplDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneladdEmplDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneladdEmplDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneladdEmplDataLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabeleID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEmplShowBeforeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeleName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeleLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeleDateOfBirth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneladdEmplDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldeedd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeledd)
                    .addComponent(jLabelemm)
                    .addComponent(jTextFieldemm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeleyyyy)
                    .addComponent(jTextFieldeyyyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeleNationality)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldeNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeleHourTax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldeHourTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelePositionName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldePositionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnEmplsSaveAddedEmpl.setText("SaveToFile");
        btnEmplsSaveAddedEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmplsSaveAddedEmplActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddNewEmplLayout = new javax.swing.GroupLayout(jPanelAddNewEmpl);
        jPanelAddNewEmpl.setLayout(jPanelAddNewEmplLayout);
        jPanelAddNewEmplLayout.setHorizontalGroup(
            jPanelAddNewEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddNewEmplLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPaneladdEmplData, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAddNewEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddNewEmplLayout.createSequentialGroup()
                        .addGroup(jPanelAddNewEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAddNewEmplLayout.createSequentialGroup()
                                .addComponent(btnAddEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)
                                .addComponent(btnEmplsSaveAddedEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addGroup(jPanelAddNewEmplLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textAreaShowListAfterAddedEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanelAddNewEmplLayout.createSequentialGroup()
                        .addComponent(jLabelErrorMessageAddEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelAddNewEmplLayout.setVerticalGroup(
            jPanelAddNewEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddNewEmplLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddNewEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAddNewEmplLayout.createSequentialGroup()
                        .addComponent(btnAddEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanelAddNewEmplLayout.createSequentialGroup()
                        .addComponent(jLabelErrorMessageAddEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAddNewEmplLayout.createSequentialGroup()
                        .addComponent(btnEmplsSaveAddedEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(textAreaShowListAfterAddedEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAddNewEmplLayout.createSequentialGroup()
                .addComponent(jPaneladdEmplData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add new Employee", jPanelAddNewEmpl);

        javax.swing.GroupLayout EmplMenuPanelLayout = new javax.swing.GroupLayout(EmplMenuPanel);
        EmplMenuPanel.setLayout(EmplMenuPanelLayout);
        EmplMenuPanelLayout.setHorizontalGroup(
            EmplMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmplMenuPanelLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );
        EmplMenuPanelLayout.setVerticalGroup(
            EmplMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmplMenuPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneEW.addTab("Employee Menu", EmplMenuPanel);

        jTextFieldWageFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWageFilePathActionPerformed(evt);
            }
        });
        jTextFieldWageFilePath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldWageFilePathKeyPressed(evt);
            }
        });

        jLabelWageFileWhours.setText("Enter file of working hours (Employee ID _ work hours)");

        jButtonWageMakeNewFile.setText("MakeNewFile");
        jButtonWageMakeNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWageMakeNewFileActionPerformed(evt);
            }
        });

        jButtonWageShowHours.setText("ShowHours");
        jButtonWageShowHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWageShowHoursActionPerformed(evt);
            }
        });

        jButtonWageCalculateWage.setText("CalculateWage");
        jButtonWageCalculateWage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWageCalculateWageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WageMenuPanelLayout = new javax.swing.GroupLayout(WageMenuPanel);
        WageMenuPanel.setLayout(WageMenuPanelLayout);
        WageMenuPanelLayout.setHorizontalGroup(
            WageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WageMenuPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(WageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WageMenuPanelLayout.createSequentialGroup()
                        .addGroup(WageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonWageShowHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonWageCalculateWage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addComponent(WageTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE))
                    .addGroup(WageMenuPanelLayout.createSequentialGroup()
                        .addGroup(WageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelWageFileWhours)
                            .addComponent(jTextFieldWageFilePath)
                            .addComponent(jLabelWageEnterFileMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jButtonWageMakeNewFile)))
                .addGap(23, 23, 23))
        );
        WageMenuPanelLayout.setVerticalGroup(
            WageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WageMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWageFileWhours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldWageFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWageEnterFileMessage)
                    .addComponent(jButtonWageMakeNewFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WageTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(WageMenuPanelLayout.createSequentialGroup()
                        .addComponent(jButtonWageShowHours, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonWageCalculateWage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPaneEW.addTab("Wage Menu", WageMenuPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneEW, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneEW, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String employeeFileName() throws Exception {
        String employeeFile = tfEnterFileEmpl.getText();
        boolean checksuffix = employeeFile.endsWith(".txt") || employeeFile.endsWith(".dat");
        if (checksuffix) {
            return employeeFile;
        } else {
            Exception IllegalInputFromUser = new Exception();
            throw IllegalInputFromUser;
        }
    }

    private void tfEnterFileEmplKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEnterFileEmplKeyPressed
        EmployeeTextArea.setText("");
        pay = new PayrollEditor();
        String employeeFile = null;

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                employeeFile = employeeFileName();
            } catch (Exception ex) {
                lbMakeFileMessage.setText("Wrong file format - must be .txt or .dat");
                ex.getStackTrace();
            }
            boolean makingDir = Writer.dataDirectory.mkdir();
            if(makingDir) lbMakeFileMessage.setText("New directory has been created, press enter to continue");
            File file = new File(Writer.dataDirectory, employeeFile);
            if (file.exists()) {
                try {
                    pay.loadEmployees(employeeFile);
                    lbMakeFileMessage.setText("File have been loaded");
                } catch (IOException ex) {
                    lbMakeFileMessage.setText("Error in loadEmployees from this file");
                }
            } else {
                lbMakeFileMessage.setText("This file does not exist. Press MakeNewFile to create a new file");
            }
        }
    }//GEN-LAST:event_tfEnterFileEmplKeyPressed

    private void btnMakeNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeNewFileActionPerformed
        String employeeFile = null;
        try {
            employeeFile = employeeFileName();
        } catch (Exception ex) {
            ex.getStackTrace();
        }
        File file = new File(Writer.dataDirectory, employeeFile);
        try {
            if (!file.exists()) {
                file.createNewFile();
                lbMakeFileMessage.setText("New file has been made.");
            } else {
                lbMakeFileMessage.setText("This file already exists");
            }
        } catch (IOException ex) {
            lbMakeFileMessage.setText("Creating new file failed!!!");
        }
    }//GEN-LAST:event_btnMakeNewFileActionPerformed

    private void btnShowEmplsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowEmplsActionPerformed
        String emplInfo = pay.getEmployeesInfo();
        emplInfo.split("[\n]");
        EmployeeTextArea.setText(emplInfo);
    }//GEN-LAST:event_btnShowEmplsActionPerformed

    public static Employee addEmployee() {
        jLabelErrorMessageAddEmpl.setText("");
        Employee e;
        String id, fname, lname, dd, mm, yyyy, nationality, htax, job;
        try {
            id = jTextFieldeID.getText();
            fname = jTextFieldeName.getText();
            lname = jTextFieldeLastName.getText();
            dd = jTextFieldeedd.getText();
            mm = jTextFieldemm.getText();
            yyyy = jTextFieldeyyyy.getText();
            nationality = jTextFieldeNationality.getText();
            htax = jTextFieldeHourTax.getText();
            job = jTextFieldePositionName.getText();
            if (job.matches("[a-zA-Z0-9._-]+[ ]+[a-zA-Z0-9._-]+")) {
                job = job.replace(" ", "_");
            }
            int eid = Integer.parseInt(id);
            int day = Integer.parseInt(dd);
            int month = Integer.parseInt(mm);
            int year = Integer.parseInt(yyyy);
            double hourTax = Double.parseDouble(htax);
            Tax tax = new Tax(hourTax, job);
            e = new Employee(eid, fname, lname, day, month, year, nationality, tax);
            return e;
        } catch (NumberFormatException ex) {
            jLabelErrorMessageAddEmpl.setText("Invalid input - id,dd,mm,yyyy,hourtax must be number");
        }
        return null;
    }

    private void btnAddEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmplActionPerformed
        try {
            Employee e = addEmployee();
            pay.addEmployeeToList(e);
        } catch (Exception ex) {
            jLabelErrorMessageAddEmpl.setText("Invalid input - wrong date");
        }
        String emplInfo = pay.getEmployeesInfo();
        emplInfo.split("[\n]");
        textAreaShowListAfterAddedEmpl.setText(emplInfo);
    }//GEN-LAST:event_btnAddEmplActionPerformed

    private void btnEmplsSortByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmplsSortByIDActionPerformed
        String emplInfo = pay.getEmployeesInfoSortedByID();
        emplInfo.split("[\n]");
        EmployeeTextArea.setText(emplInfo);
    }//GEN-LAST:event_btnEmplsSortByIDActionPerformed

    private void btnEmplsSortByFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmplsSortByFirstNameActionPerformed
        String emplInfo = pay.getEmployeesInfoSortedByFirstName();
        emplInfo.split("[\n]");
        EmployeeTextArea.setText(emplInfo);
    }//GEN-LAST:event_btnEmplsSortByFirstNameActionPerformed

    private void btnEmplsSortByLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmplsSortByLastNameActionPerformed
        String emplInfo = pay.getEmployeesInfoSortedByLastName();
        emplInfo.split("[\n]");
        EmployeeTextArea.setText(emplInfo);
    }//GEN-LAST:event_btnEmplsSortByLastNameActionPerformed

    private void btnEmplsSaveAddedEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmplsSaveAddedEmplActionPerformed
        String employeeFile = null;
        try {
            employeeFile = employeeFileName();
        } catch (Exception ex) {
            jLabelErrorMessageAddEmpl.setText("File finding - failed");
            ex.getStackTrace();
        }
        try {
            pay.saveAddedEmployees(employeeFile);
        } catch (IOException ex) {
            jLabelErrorMessageAddEmpl.setText("Saving data to file - failed");
        }
        String emplInfo = pay.getEmployeesInfo();
        emplInfo.split("[\n]");
        textAreaShowListAfterAddedEmpl.setText(emplInfo);
    }//GEN-LAST:event_btnEmplsSaveAddedEmplActionPerformed

    protected String getEmployeeWithHeaderToString(Employee e) {
        StringBuilder sb = new StringBuilder("");
        sb.append(String.format("%-5s%-20s%-20s%-12s%-6s%-8s%-20s%n", "ID", "jméno", "příjmění", "narození", "země", "Kč/hod", "pozice"));
        sb.append(e.getEmployeeToString());
        return sb.toString();
    }

    private void btnEmplShowBeforeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmplShowBeforeAddActionPerformed
        try {
            Employee e = addEmployee();
            textAreaShowListAfterAddedEmpl.setText(getEmployeeWithHeaderToString(e));
        } catch (Exception ex) {
            jLabelErrorMessageAddEmpl.setText("Invalid input - wrong date");
        }
    }//GEN-LAST:event_btnEmplShowBeforeAddActionPerformed

    private void btnFindEmplByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindEmplByIDActionPerformed
        String sid = jTextFieldEmplSearchForID.getText();
        try {
            int id = Integer.parseInt(sid);
            Employee e = pay.findEmployee(id);
            EmployeeTextArea.setText(getEmployeeWithHeaderToString(e));
        } catch (NoSuchElementException e) {
            EmployeeTextArea.setText("Can not find this employee's ID");
        }

    }//GEN-LAST:event_btnFindEmplByIDActionPerformed

    private String wageFileName() throws Exception {
        String wageFile = jTextFieldWageFilePath.getText();
        boolean checksuffix = wageFile.endsWith(".txt") || wageFile.endsWith(".dat");
        if (checksuffix) {
            return wageFile;
        } else {
            Exception IllegalInputFromUser = new Exception();
            throw IllegalInputFromUser;
        }
    }

    private void jTextFieldWageFilePathKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldWageFilePathKeyPressed
        String wageFile = null;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                wageFile = wageFileName();
                jLabelWageEnterFileMessage.setText("File have been found...");
            } catch (NullPointerException npe) {
                jLabelWageEnterFileMessage.setText("Employees file not found or is empty");
            } catch (Exception ex) {
                jLabelWageEnterFileMessage.setText("Wrong file format - must be .txt or .dat");
                ex.getStackTrace();
            }
            File file = new File(Writer.dataDirectory, wageFile);
            file.mkdir();
            if (file.exists()) {
                try {
                    pay.loadHours(wageFile);
                    jLabelWageEnterFileMessage.setText("File have been loaded");
                } catch (NoSuchElementException e) {
                    jLabelWageEnterFileMessage.setText("The Employee ID could nor be found");
                } catch (IOException ex) {
                    jLabelWageEnterFileMessage.setText("Parsing hours failed");
                }
            } else {
                jLabelWageEnterFileMessage.setText("This file does not exist. Press MakeNewFile to create a new file");
            }
        }
    }//GEN-LAST:event_jTextFieldWageFilePathKeyPressed

    private void jButtonWageMakeNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWageMakeNewFileActionPerformed
        String wageFile = null;
        try {
            wageFile = wageFileName();
        } catch (Exception ex) {
            ex.getStackTrace();
        }
        File file = new File(Writer.dataDirectory, wageFile);
        file.mkdir();
        jLabelWageEnterFileMessage.setText("Making new dir");
        try {
            if (!file.exists()) {
                file.createNewFile();
                jLabelWageEnterFileMessage.setText("New file has been made.");
            } else {
                jLabelWageEnterFileMessage.setText("This file already exists");
            }
        } catch (IOException ex) {
            jLabelWageEnterFileMessage.setText("Creating new file failed!!!");
        }
    }//GEN-LAST:event_jButtonWageMakeNewFileActionPerformed

    private void jButtonWageShowHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWageShowHoursActionPerformed
        String wageInfo = pay.getHoursInfo();
        wageInfo.split("[\n]");
        WageTextArea.setText(wageInfo);
    }//GEN-LAST:event_jButtonWageShowHoursActionPerformed

    private void jButtonWageCalculateWageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWageCalculateWageActionPerformed
        pay.calculateWages();
        String wageInfo = pay.getWagesInfo();
        wageInfo.split("[\n]");
        WageTextArea.setText(wageInfo);
    }//GEN-LAST:event_jButtonWageCalculateWageActionPerformed

    private void jTextFieldWageFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWageFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWageFilePathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmplMenuPanel;
    private java.awt.TextArea EmployeeTextArea;
    private javax.swing.JPanel WageMenuPanel;
    private java.awt.TextArea WageTextArea;
    private javax.swing.JButton btnAddEmpl;
    private javax.swing.JButton btnEmplShowBeforeAdd;
    private javax.swing.JButton btnEmplsSaveAddedEmpl;
    private javax.swing.JButton btnEmplsSortByFirstName;
    private javax.swing.JButton btnEmplsSortByID;
    private javax.swing.JButton btnEmplsSortByLastName;
    private javax.swing.JButton btnFindEmplByID;
    private javax.swing.JButton btnMakeNewFile;
    private javax.swing.JButton btnShowEmpls;
    private javax.swing.JButton jButtonWageCalculateWage;
    private javax.swing.JButton jButtonWageMakeNewFile;
    private javax.swing.JButton jButtonWageShowHours;
    private javax.swing.JLabel jLabelEmplsSorting;
    private static javax.swing.JLabel jLabelErrorMessageAddEmpl;
    private javax.swing.JLabel jLabelSearchForID;
    private static javax.swing.JLabel jLabelWageEnterFileMessage;
    private javax.swing.JLabel jLabelWageFileWhours;
    private javax.swing.JLabel jLabeleDateOfBirth;
    private javax.swing.JLabel jLabeleHourTax;
    private javax.swing.JLabel jLabeleID;
    private javax.swing.JLabel jLabeleLastName;
    private javax.swing.JLabel jLabeleName;
    private javax.swing.JLabel jLabeleNationality;
    private javax.swing.JLabel jLabelePositionName;
    private javax.swing.JLabel jLabeledd;
    private javax.swing.JLabel jLabelemm;
    private javax.swing.JLabel jLabeleyyyy;
    private javax.swing.JPanel jPanelAddNewEmpl;
    private javax.swing.JPanel jPanelLoadShowEmpls;
    private javax.swing.JPanel jPaneladdEmplData;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneEW;
    private static javax.swing.JTextField jTextFieldEmplSearchForID;
    private javax.swing.JTextField jTextFieldWageFilePath;
    private static javax.swing.JTextField jTextFieldeHourTax;
    private static javax.swing.JTextField jTextFieldeID;
    private static javax.swing.JTextField jTextFieldeLastName;
    private static javax.swing.JTextField jTextFieldeName;
    private static javax.swing.JTextField jTextFieldeNationality;
    private static javax.swing.JTextField jTextFieldePositionName;
    private static javax.swing.JTextField jTextFieldeedd;
    private static javax.swing.JTextField jTextFieldemm;
    private static javax.swing.JTextField jTextFieldeyyyy;
    private javax.swing.JLabel lbMakeFileMessage;
    private static java.awt.TextArea textAreaShowListAfterAddedEmpl;
    private java.awt.TextField tfEnterFileEmpl;
    // End of variables declaration//GEN-END:variables
}
